export const ActionTypes = {
  REGISTER_REQUEST:"REGISTER_REQUEST",
  REGISTER_SUCCESS:"REGISTER_SUCCESS",
  REGISTER_FAILURE:"REGISTER_FAILURE",
  SET_ARTICLES: "SET_ARTICLES",
  SELECTED_ARTICLES: "SELECTED_ARTICLES",
};
