const GET_ARTICLES_ACTION = "get/articles";
const GET_ARTICLE_ACTION = "get/article";
const SET_ARTICLE_ACTION = "set/article"
const DELETE_ARTICLE_ACTION = "delete/article"

export { GET_ARTICLES_ACTION, GET_ARTICLE_ACTION, SET_ARTICLE_ACTION,DELETE_ARTICLE_ACTION };
